services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d
      - ./db/conf/:/etc/mysql/conf.d
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./cloudserver:/docker-entrypoint-init.d
    command: server /data --console-address ":9001"
    env_file:
      - .env
