services:
  db:
    image: mysql:8.0
    container_name: web-server-template-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d
      - ./db/conf/:/etc/mysql/conf.d
    env_file:
      - .env
